apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: pulsepredict
    user: pulsepredict
    secureJsonData:
      password: changeme
    jsonData:
      sslmode: disable
      postgresVersion: 1600
